export const SET_SEARCH_USER_INVITATION_QUERY = "SET_SEARCH_USER_INVITATION_QUERY";
export const SET_SEARCH_USER_INVITATION_RESULT = "SET_SEARCH_USER_INVITATION_RESULT";
export const ADD_USER_TO_INVITE_TO_LIST = "ADD_USER_TO_INVITE_TO_LIST";
export const REMOVE_USER_FROM_INVITATIONS_LIST = "REMOVE_USER_FROM_INVITATIONS_LIST";
export const RESET_INVITATIONS_DATA = "RESET_INVITATIONS_DATA";
