export const SET_SEARCH_USER_INVITATION_QUERY = "SET_SEARCH_USER_INVITATION_QUERY";
export const SET_SEARCH_USER_INVITATION_RESULT = "SET_SEARCH_USER_INVITATION_RESULT";
export const ADD_USER_TO_INVITE_TO_LIST = "ADD_USER_TO_INVITE_TO_LIST";
