export const ADD_MESSAGE_TO_CHAT = "ADD_MESSAGE_TO_CHAT";
export const RESET_CHAT_DATA = "RESET_CHAT_DATA";
export const ADD_MESSAGES_LOADED = "ADD_MESSAGES_LOADED";
export const SET_REQUESTING_CHAT_MESSAGES = "SET_REQUESTING_CHAT_MESSAGES";
