export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_INVITATIONS_DATA = "SET_USER_INVITATIONS_DATA";
export const RESET_INVITATIONS_COUNT_NOTIFICATION = "RESET_INVITATIONS_COUNT_NOTIFICATION";
export const REPLY_TO_INVITATION = "REPLY_TO_INVITATION";
export const ADD_NEW_GROUP = "ADD_NEW_GROUP";
