export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_INVITATIONS_DATA = "SET_USER_INVITATIONS_DATA";
export const RESET_INVITATIONS_COUNT_NOTIFICATION = "RESET_INVITATIONS_COUNT_NOTIFICATION";
