export const SET_USERNAME_LOGIN = "SET_USERNAME_LOGIN";
export const SET_PASSWORD_LOGIN = "SET_PASSWORD_LOGIN";
export const SET_ERROR_LOGIN = "SET_ERROR_LOGIN";
export const RESET_DATA_LOGIN = "RESET_DATA_LOGIN";
