export const SET_REALNAME_SIGNUP = "SET_REALNAME_SIGNUP";
export const SET_USERNAME_SIGNUP = "SET_USERNAME_LOGIN";
export const SET_EMAIL_SIGNUP = "SET_EMAIL_SIGNUP";
export const SET_PASSWORD_SIGNUP = "SET_PASSWORD_SIGNUP";
export const SET_CONFIRM_PASSWORD_SIGNUP = "SET_CONFIRM_PASSWORD_SIGNUP";
export const SET_ERROR_SIGNUP = "SET_ERROR_SIGNUP";